export const articles = [
  {
    id: '1',
    title: '文章标题1',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介1',
    content: '这里是文章1的具体内容...',
    views: 100,
    tags: ['技术', '高人气'],
  },
  {
    id: '2',
    title: '文章标题2',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介2',
    content: '这里是文章2的具体内容...',
    views: 80,
    tags: ['教程'],
  },
  // 继续添加更多文章
  {
    id: '3',
    title: '文章标题3',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介3',
    content: '这里是文章3的具体内容...',
    views: 60,
    tags: ['技术'],
  },
  {
    id: '4',
    title: '文章标题4',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介4',
    content: '这里是文章4的具体内容...',
    views: 50,
    tags: ['新闻'],
  },
  {
    id: '5',
    title: '文章标题5',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介5',
    content: '这里是文章5的具体内容...',
    views: 45,
    tags: ['技术', '教程'],
  },
  {
    id: '6',
    title: '文章标题6',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介6',
    content: '这里是文章6的具体内容...',
    views: 40,
    tags: ['教程'],
  },
  {
    id: '7',
    title: '文章标题7',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介7',
    content: '这里是文章7的具体内容...',
    views: 35,
    tags: ['技术'],
  },
  {
    id: '8',
    title: '文章标题8',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介8',
    content: '这里是文章8的具体内容...',
    views: 30,
    tags: ['高人气'],
  },
  {
    id: '9',
    title: '文章标题9',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介9',
    content: '这里是文章9的具体内容...',
    views: 25,
    tags: ['新闻', '教程'],
  },
  {
    id: '10',
    title: '文章标题10',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介10',
    content: '这里是文章10的具体内容...',
    views: 20,
    tags: ['技术'],
  },
  {
    id: '11',
    title: '文章标题11',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介11',
    content: '这里是文章11的具体内容...',
    views: 15,
    tags: ['高人气'],
  },
  {
    id: '12',
    title: '文章标题12',
    cover: 'https://via.placeholder.com/150',
    summary: '文章简介12',
    content: '这里是文章12的具体内容...',
    views: 10,
    tags: ['新闻'],
  },
];
